name: Java with Maven

on:
  push:
    branches:
      - main

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile
        run: mvn compile

  Test:
    runs-on: ubuntu-latest
    needs: Compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn test -DskipTests=true

  Package:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Package
        run: mvn package -DskipTests=true
    
  Trivy_Scan :
    runs-on: ubuntu-latest
    needs:  Package
    steps:
      - uses: actions/checkout@v4
      - name : Installation of the Trivy
        run: |
              sudo apt-get install wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
              sudo apt-get update -y
              sudo apt-get install trivy -y
              
      - name: Trivy Sacn the file system    
        run: trivy fs --format json -o fs.report json
              
  Gitleaks :
        runs-on: ubuntu-latest
        needs: Trivy_Scan
        steps:
        - uses: actions/checkout@v4
        - name : San the Vulnerability
          run: |
                sudo apt-get install gitleaks      
      
      
